// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversitarySystem.EFCore.Context;

#nullable disable

namespace UniversitarySystem.EFCore.Migrations
{
    [DbContext(typeof(UniversitarySystemContextSQL))]
    [Migration("20241006232154_NewColumnsTableCollegeCareers")]
    partial class NewColumnsTableCollegeCareers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.AddressEntity", b =>
                {
                    b.Property<int>("IdAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAddress"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdAddress");

                    b.HasIndex("CityId");

                    b.HasIndex("StudentId");

                    b.ToTable("DetailAddress", (string)null);
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.BloodTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.ToTable("BloodTypes");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.CityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.CollegeCareerEntity", b =>
                {
                    b.Property<int>("IdCollegeCareer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCollegeCareer"));

                    b.Property<string>("CollegeCareer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("TypeCareersId")
                        .HasColumnType("int");

                    b.HasKey("IdCollegeCareer");

                    b.HasIndex("TypeCareersId");

                    b.ToTable("CollegeCareers");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.DetailsEntity", b =>
                {
                    b.Property<int>("IdDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetail"));

                    b.Property<int>("DetailTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdDetail");

                    b.HasIndex("DetailTypeId");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.DetailsTypeEntity", b =>
                {
                    b.Property<int>("IdDetailType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetailType"));

                    b.Property<string>("DetailTypeDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdDetailType");

                    b.ToTable("DetailsTypeEntity");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.ProvinceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.PsychophysicalEntity", b =>
                {
                    b.Property<int>("IdPsychophysical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPsychophysical"));

                    b.Property<string>("AdditionalComments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BloodTypeId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("IdPsychophysical");

                    b.HasIndex("BloodTypeId");

                    b.HasIndex("StudentId");

                    b.ToTable("Psychophysicals");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.Psychophysical_DetailsEntity", b =>
                {
                    b.Property<int>("DetailId")
                        .HasColumnType("int");

                    b.Property<int>("PsychophysicalId")
                        .HasColumnType("int");

                    b.HasKey("DetailId", "PsychophysicalId");

                    b.HasIndex("PsychophysicalId");

                    b.ToTable("Details.Psychophysicals", (string)null);
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.StudentEntity", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStudent"));

                    b.Property<string>("CUIL")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateRegistry")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumberPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("IdStudent");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.Student_CollegeCareerEntity", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CollegeCareerId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CollegeCareerId");

                    b.HasIndex("CollegeCareerId");

                    b.ToTable("CollegeCareers.Students", (string)null);
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.TitleEntity", b =>
                {
                    b.Property<int>("IdTittle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTittle"));

                    b.Property<DateOnly>("EgressDate")
                        .HasColumnType("date");

                    b.Property<string>("HighSchool")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecondaryDegree")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("IdTittle");

                    b.HasIndex("StudentId");

                    b.ToTable("Title", (string)null);
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.TypeCareersEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TypeCareers");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.AddressEntity", b =>
                {
                    b.HasOne("UniversitarySystem.UsesCases.POCOEntities.CityEntity", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversitarySystem.UsesCases.POCOEntities.StudentEntity", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.CityEntity", b =>
                {
                    b.HasOne("UniversitarySystem.UsesCases.POCOEntities.ProvinceEntity", "Province")
                        .WithMany("City")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.CollegeCareerEntity", b =>
                {
                    b.HasOne("UniversitarySystem.UsesCases.POCOEntities.TypeCareersEntity", "TypeCareers")
                        .WithMany()
                        .HasForeignKey("TypeCareersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeCareers");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.DetailsEntity", b =>
                {
                    b.HasOne("UniversitarySystem.UsesCases.POCOEntities.DetailsTypeEntity", "DetailType")
                        .WithMany()
                        .HasForeignKey("DetailTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetailType");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.PsychophysicalEntity", b =>
                {
                    b.HasOne("UniversitarySystem.UsesCases.POCOEntities.BloodTypeEntity", "BloodType")
                        .WithMany()
                        .HasForeignKey("BloodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversitarySystem.UsesCases.POCOEntities.StudentEntity", "Student")
                        .WithMany("Psychophysicals")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodType");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.Psychophysical_DetailsEntity", b =>
                {
                    b.HasOne("UniversitarySystem.UsesCases.POCOEntities.DetailsEntity", "Detail")
                        .WithMany("PsychophysicalsDetails")
                        .HasForeignKey("DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversitarySystem.UsesCases.POCOEntities.PsychophysicalEntity", "Psychophysical")
                        .WithMany("PsychophysicalsDetails")
                        .HasForeignKey("PsychophysicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detail");

                    b.Navigation("Psychophysical");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.Student_CollegeCareerEntity", b =>
                {
                    b.HasOne("UniversitarySystem.UsesCases.POCOEntities.CollegeCareerEntity", "CollegeCareer")
                        .WithMany("StudentCollegeCareers")
                        .HasForeignKey("CollegeCareerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversitarySystem.UsesCases.POCOEntities.StudentEntity", "Student")
                        .WithMany("StudentCollegeCareers")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollegeCareer");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.TitleEntity", b =>
                {
                    b.HasOne("UniversitarySystem.UsesCases.POCOEntities.StudentEntity", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.CollegeCareerEntity", b =>
                {
                    b.Navigation("StudentCollegeCareers");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.DetailsEntity", b =>
                {
                    b.Navigation("PsychophysicalsDetails");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.ProvinceEntity", b =>
                {
                    b.Navigation("City");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.PsychophysicalEntity", b =>
                {
                    b.Navigation("PsychophysicalsDetails");
                });

            modelBuilder.Entity("UniversitarySystem.UsesCases.POCOEntities.StudentEntity", b =>
                {
                    b.Navigation("Psychophysicals");

                    b.Navigation("StudentCollegeCareers");
                });
#pragma warning restore 612, 618
        }
    }
}
